import Head from "next/head";
import { Sidebar, Feed, Widget } from "components/pages";
export default function Home({ data, news }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen max-w-7xl mx-auto ">
        <Sidebar />
        <Feed />
        <Widget data={data} news={news} />
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const data = await fetch("https://randomuser.me/api/?results=400")
    .then((res) => res.json())
    .catch((err) => console.log(err));
  const news = await fetch(
    `https://newsapi.org/v2/everything?q=manchester-united&apiKey=${process.env.API_KEY}`
  )
    .then((res) => res.json())
    .catch((err) => console.log(err));
  return {
    props: {
      data: data?.results,
      news: news?.articles,
    },
  };
};
